### ISSUE TITLE
js error Uncaught TypeError: Cannot read property 'call' of null

### ISSUE THREAD

**Issue by spaceblock** [fulcrologic/websocket-demo#2]
In last master

1. Uncaught TypeError: Cannot read property 'call' of null
2. [ 17.575s] [fulcro.client.impl.application] Mutation  websocket-demo.api/login  failed with exception Error: Assert failed: Path [:root/all-users] for append must target an app-state vector.
(vector? (get-in state data-path))

**Comment by spaceblock** [comment]
This error is gone after I am go in Chrome (not FF) and set in settings Console, Enable custom formatters. why this?

**Comment by awkay** [comment]
Development mode does use preloads that are targeted chrome extensions. It is recommended you do primary development in Chrome. All browsers should be fine for runtime, and you can remove the preloads (in the build configuration) if you want to develop against other browsers.
